openapi: 3.1.0
info:
  title: Data Compliance
  version: 1.0.0
paths:
  /api/v1/data-subject-request:
    post:
      operationId: delete-all-data-associated-with-a-chatters-email-address
      summary: Delete all data associated with a chatter's email address
      description: >-
        Deletes all data associated with the provided chatter's email address linked to the bot. Replace `example` with
        your agent's handle. A successful call returns the chatter's email supplied (null if email field was not
        supplied) in the request whose data will be deleted from Ada's systems. In order to ensure emails are properly
        linked to a chatter record, ensure the capture block validation when capturing email is set to `@
        Email.`<br><br> **Note for multiple participant emails:** If you are requesting data deletion for one chatter’s
        email address and they are a participant in a conversation that has multiple email participants (i.e., Email
        thread with additional recipients in CC), the entire transcript will be deleted for all participants.
      tags:
        - subpackage_deleteChatterData
      parameters:
        - name: Authorization
          in: header
          description: Bearer authentication
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request was successfully ingested into Ada's system.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteSubjectResponse'
        '400':
          description: Invalid request body or headers.
          content:
            application/json:
              schema:
                description: Any type
        '401':
          description: Authentication token is invalid or does not have the correct permissions. Try generating a new token.
          content:
            application/json:
              schema:
                description: Any type
        '500':
          description: Something went wrong on Ada's end.
          content:
            application/json:
              schema:
                description: Any type
        '502':
          description: Nginx gateway issue on Ada's servers.
          content:
            application/json:
              schema:
                description: Any type
        '503':
          description: Server temporarily unable to handle the request.
          content:
            application/json:
              schema:
                description: Any type
        '504':
          description: Temporary infrastructure error on Ada's servers.
          content:
            application/json:
              schema:
                description: Any type
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteSubjectRequest'
servers:
  - url: https://example.ada.support
    description: ada
  - url: https://example.att.ada.support
    description: att.ada
  - url: https://example.maple.ada.support
    description: maple.ada
  - url: https://example.ficanex.ada.support
    description: ficanex.ada
  - url: https://example.eu.ada.support
    description: eu.ada
components:
  schemas:
    TokenType:
      type: string
      enum:
        - ERASURE
      description: Type of data subject request. Must be set to ERASURE.
      title: TokenType
    EmailType:
      type: string
      description: Email of the chatter whose data you wish to delete from Ada's systems.
      title: EmailType
    IdentifiersTypeItemsType:
      type: string
      enum:
        - email
        - chatter_id
      title: IdentifiersTypeItemsType
    IdentifiersTypeItems:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/IdentifiersTypeItemsType'
        value:
          type: string
      title: IdentifiersTypeItems
    IdentifiersType:
      type: array
      items:
        $ref: '#/components/schemas/IdentifiersTypeItems'
      description: List containing extra identifiers sent with the data subject request.
      title: IdentifiersType
    DeleteSubjectRequest:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/TokenType'
        email:
          $ref: '#/components/schemas/EmailType'
        identifiers:
          $ref: '#/components/schemas/IdentifiersType'
      required:
        - type
      title: DeleteSubjectRequest
    DeleteSubjectResponse:
      type: object
      properties:
        email:
          $ref: '#/components/schemas/EmailType'
      title: DeleteSubjectResponse
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
